apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  namespace: sre-lab
  labels:
    app: inventory-api
spec:
  replicas: 2 # Vamos rodar 2 pods para testar balanceamento futuro
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
        - name: inventory-api
          image: inventory-api:v2
          imagePullPolicy: Never # OBRIGATÃ“RIO para imagens locais no K3s
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:4317"
          ports:
            - containerPort: 3333
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
