apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
  namespace: sre-lab
spec:
  selector:
    app: inventory-api
  type: LoadBalancer # O K3s simula um LoadBalancer localmente
  ports:
    - protocol: TCP
      port: 8888      # Porta externa livre
      targetPort: 3333 # Porta onde o container escuta
